env:
  global:
  - secure: kLbgroo1h/jMGmBSk+IJOL87hVE/cqsrtFYIt5tLkxiBPBG7/nnumJJEBhfHJKRnp1idLBJkwI7EELYBWdegk+kMrODo8FgXhtBehjCU4zf5DBnsgEfpF9JaR/rGDot9NTK2dYd1ysQKhIo/xQicrz91TwpalzH8HcxDSVLOon+5Bj7ijw477gZPK0hnAau9rZniu44M0ve6SLNlQwPoNTQ+aQnAxxReUQC94NBZzD9Y0Fze6+JdVbjcSrJPD+s8YpgHYIUe9ywfSVVbkMqsnp93lsKHAbboeRHyf3TfmOCM2t/3kex3rykAXCBJER9ImP8erV9BjVEwyDVWqxt2cr4DdoUI8Z5IzIFgezoDQZSwolU2m3eQyKed1tcvRQdkhdYEE8t4e+ZMpVcRxiWJw2OHT1skhmNRfagBgYjLmUzwcDHQWRsQiMY9fk1ax87xcCXac74kS+IF6Aqx2gcRR7MdarNh7bJw08SZnvj8cm7obcJ0PJtriBmIUzuQ7u5fJznmDBkYotunhRxgm6sptk03oMIsw/m/0WKkYgdu/UEr2x8VbWG+NP9zp5X26bDp31Xm3XauTX1NPc+tk17SImZ9fyFhvgc+iMJMoXA3gNH13EVVwRmewKkRkKKdjiRLZxmGiFBzDymfcsA48rMmXQ9BKHUiReXxVMbInhoHX5A=
sudo: false
language: node_js
node_js:
- '10'
before_install:
- npm i -g pnpm
install:
- pnpm install
before_script:
- pnpm run lint
- chmod u+x ./bin/build
- chmod u+x ./bin/travis-push-update
script:
- "./bin/build ../gh-pages"
after_success:
- "./bin/travis-push-update"
notifications:
  email: false
