sudo: false
language: node_js
node_js:
- '10'
before_install:
- npm i -g pnpm
install:
- pnpm install
before_script:
- pnpm run lint
- chmod u+x ./bin/build
- chmod u+x ./bin/travis-push-update
script:
- "./bin/build ../gh-pages"
after_success:
- "./bin/travis-push-update"
notifications:
  email: false
env:
  global:
    secure: L+3BiOQV8Oq0A1E9AYPhrYOopZ3M2Lm3cU32dp1Wq/O2S+ETehk11fqkwAQ6+di2vsApmXQlvDxsquEO6UrUTrpov8lL53WnViUnJNJSS1UCp4AQnCwlgMQWW37dw5VpfenLP9jBJt0EEyDW5WEuMpnxf4NugYSXen5An3ouAfAkeg72zGjdz+rsInKP9x9GqVh76F+FPdHyY9vXcnXqWRIHYhWNjoWONf7I7MC1NMKypwUzd1yOxJCVofuYcaP1318JMHDwvIqA4IHVBiT8Op8HI/FD1lc9v0zRBmnWDGnhWWehxdnupQ60XV4vvG5fzJ5IfJFXRusoEjUPgUS7ws4ZN1dGf/vIGaiUY96tKL97lxQu8ew9T0+6ldLSV9codA+5QWIvzZBPuKsyqoRystJQMJmza26Sqh77+R9OdQciJnIH5shTEjCQhxhdnwo9CNnX6CprVVmeTYSTnWEiMj8J9DMvV97d5mpCGd/AgClKkNb4bUKMb0ZlGNSi7pRKhTV0zw1bWSgMrwB5q/OGWQZ8HXlbSHFr8lfSRKRU8d/ThEBmWaRJV3ARZPfCfsia0O4KpxR36RKUdEMkHXBrsXe53SWGuyWONgY+/R/4rCD+SXGyfTAQ6xdGDRFIvgaauQ2TYhoE3/ZCOsQPJdXF377ApsgcAgvCzGQI5XEpfAg=
