sudo: false
language: node_js
node_js:
- '10'
before_install:
- npm i -g pnpm
install:
- pnpm install
before_script:
- pnpm run lint
- chmod u+x ./bin/build
- chmod u+x ./bin/travis-push-update
script:
- "./bin/build ../gh-pages"
after_success:
- "./bin/travis-push-update"
notifications:
  email: false
env:
  global:
    secure: G1GTa6Dm9lOn8zyToylrsjryGqUIcSDRRM4oEwIZM3g82cl3TGwbPmKmZCUCVoQOOqwATT8nV83ifsU8FeiDik3slXgsm3//TkdxMVgrNTu9kUCmdkq40tHzCtS//wgvEsyqq1HRpcubvHIeaetuEd8NuBD3+b/eDvq/yU2XOEiQn5tl9Vz9D2RGaD9ddyWS5lv/BilP0ApDH6lsD/V1HF4y60RuVSTnLcLzAk4HPJjlbNEK85nm4Snlyyslk0Mxj0eLQTeL0i4FeMWsssJFBNilzcPIWE4db4tQsF+o70MTAwJlicbU55rUKhugmrPL7acQI0rIfPaDND3YUKlPD2JjE+e61hX8x5YDtHjIcgqN66iSH7TnbkwSoqCmnMYUxHQEJHinCirqOQkh/xiJbH4yoa/lwollfWIoegMAxvG2NZwYE4TAnge/axPZcdiBnCLoB8teyvIJFA0NTbsgEaNPqQvzbOYQBJjxSBK0zp/oOUTyhWssRcvIJduMs+oToWkGV4jtCcOLA2f9t4bD+g6LG+BFpbe64/VbRHCzZKV7AQ8Rq9ZnD2n5Rb3k9FPtPTN+kuInZ7gqumsZm9Rox1Ku3MnPGfPg2zttQZfmUMKAznDxoIIW4YS1dcmpHaqjLHkj2AgmtuIMC6+M+1ls0V8KOgjdLq1Z37Ie/hCPVR4=
